apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: mysql-credentials-vault
spec:
  provider: vault
  parameters:
    vaultAddress: "http://vault.default:8200"
    roleName: "mysql-secret-role"  # Update to the Vault role associated with MySQL credentials
    objects: |
      - objectName: "mysql-credentials"  # Name of the secrets object in Vault
        secretPath: "secret/data/mysql-credentials"  # Path in Vault where MySQL credentials are stored
        secretKey: "username,password"  # Keys within the secret object containing username and password
